### ISSUE TITLE
[MARK-120] 리마인드 알림 목록 조회

### ISSUE THREAD

**Issue by HamBeomJoon** [MJU-Capstone-6/DevMark-Android#69]
## Description
리마인드 알림 목록 조회

## To-do
- [x] 리마인드 알림 목록 조회
- [x] 기타 디자인 수정
- [x] 리마인드 알림 상세 페이지로 이동
